name: issue_to_notion
on:
  issues:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: issue-to-notion
        uses: dodo4114/issue-to-notion@v1.1.1

        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          DATABASE_URL: {https://www.notion.so/7bce588000ec4ff7a59205925c79be4a?v=0210218e40d9444789fc9185c089bc81}
          PROPERTY_NAME : {YOUR PROPERTY NAME}
          STATE_OPEN : {YOUR OPEN STATE NAME}
          STATE_CLOSED : {YOUR CLOSED STATE NAME}
